import React from 'react';
import { View, Text, StyleSheet, SafeAreaView, ScrollView } from 'react-native';
import colors from '../theme/colors';
import PrimaryButton from '../components/PrimaryButton';

export default function ReferralSlipScreen({ route, navigation }) {
  const { patientDetails, riskScore, riskLevel, notes } = route.params || {};

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.slipCard}>
          <View style={styles.slipHeader}>
            <Text style={styles.appTitle}>RAKSHA AI</Text>
            <Text style={styles.slipTitle}>OFFICIAL REFERRAL SLIP</Text>
            <View style={styles.qrPlaceholder}>
              <Text style={styles.qrText}>[SECURE-ID-QR]</Text>
            </View>
          </View>

          <View style={styles.divider} />

          <View style={styles.infoGrid}>
            <View style={styles.infoRow}>
              <Text style={styles.label}>Patient Name</Text>
              <Text style={styles.value}>{patientDetails?.name}</Text>
            </View>
            <View style={styles.infoRow}>
              <Text style={styles.label}>Patient ID</Text>
              <Text style={styles.value}>{patientDetails?.patientId?.substring(0, 16)}</Text>
            </View>
            <View style={styles.infoRow}>
               <Text style={styles.label}>Risk Category</Text>
               <Text style={[styles.value, { color: riskLevel === 'HIGH' ? colors.riskHigh : colors.riskMedium, fontWeight: '800' }]}>{riskLevel}</Text>
            </View>
            <View style={styles.infoRow}>
               <Text style={styles.label}>AI Risk Score</Text>
               <Text style={styles.value}>{riskScore}/100</Text>
            </View>
          </View>

          <View style={styles.divider} />

          <View style={styles.notesSection}>
            <Text style={styles.sectionTitle}>Digital Diagnostic Notes</Text>
            <Text style={styles.notesText}>{notes || 'No additional clinical notes provided.'}</Text>
          </View>

          <View style={styles.footer}>
            <Text style={styles.footerText}>This slip is generated by Raksha AI. Please present this at the medical facility for fast-track processing.</Text>
            <Text style={styles.timestamp}>Generated on: {new Date().toLocaleString()}</Text>
          </View>
        </View>

        <PrimaryButton 
          title="Print / Save as PDF" 
          variant="primary" 
          onPress={() => {}} 
        />
        <PrimaryButton 
          title="Back to Referral List" 
          variant="outline" 
          onPress={() => navigation.goBack()} 
          style={{ marginTop: 12 }}
        />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollContent: {
    padding: 24,
  },
  slipCard: {
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 32,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 4,
  },
  slipHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  appTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primaryBlue,
    letterSpacing: 2,
    marginBottom: 4,
  },
  slipTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: 20,
  },
  qrPlaceholder: {
    width: 80,
    height: 80,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  qrText: {
    fontSize: 8,
    color: colors.textSecondary,
    textAlign: 'center',
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 24,
  },
  infoGrid: {
    gap: 16,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  value: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '600',
  },
  notesSection: {
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.textPrimary,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  notesText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 8,
  },
  footer: {
    marginTop: 32,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 10,
    color: colors.textSecondary,
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 14,
  },
  timestamp: {
    fontSize: 10,
    color: colors.textSecondary,
    marginTop: 8,
    fontWeight: '700',
  }
});
