import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import colors from '../theme/colors';

export default function ReferralSlip({ patientDetails, symptoms, riskScore, riskLevel, notes }) {
  return (
    <View style={styles.container}>
      <Text style={styles.header}>Digital Referral Slip</Text>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Patient Details</Text>
        <Text>Name: {patientDetails.name}</Text>
        <Text>Phone Number: {patientDetails.phoneNumber}</Text>
        <Text>Patient ID: {patientDetails.patientId}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Symptoms</Text>
        <Text>{symptoms}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Risk Score</Text>
        <Text>{riskScore}% ({riskLevel})</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Notes</Text>
        <Text>{notes}</Text>
      </View>

      <Text style={styles.footer}>Generated by Health Assessment App</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  header: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    color: colors.primaryBlue,
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: colors.textPrimary,
  },
  footer: {
    marginTop: 20,
    fontSize: 12,
    textAlign: 'center',
    color: 'gray',
  },
});
